name: Run Node.js Script and Commit Changes

on:
  workflow_dispatch:
  schedule:
    # Schedule to run at 9 AM UTC every day
    - cron: '43 17 * * *'

jobs:
  execute_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set Git remote URL to SSH
      run: git remote set-url origin git@github.com:lawjiahua/HeyBros-dailyQuest.git

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.1
      with:
        ssh-private-key: ${{ secrets.HEYBO_RUNS_SSH_KEY }}

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Adjust this as per your project's Node.js version

    - name: Install dependencies
      run: npm install  # Run this if your project has dependencies

    - name: Run the script
      run: node main.js

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "heybo run on $(date -u +'%Y-%m-%d')" || exit 0  # Commits with current date. Exits if nothing to commit.
        git push
